// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgauoosxacrbshfwtill.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnYXVvb3N4YWNyYnNoZnd0aWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDIyODUsImV4cCI6MjA2NDM3ODI4NX0.HwdfCzpHlpgWgyUthhJdSjeB3doltD34FgRz9wgcvYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);